

headers := $(shell find $(board_dir) -name '*.h')
c_src := $(shell find $(board_dir) -name '*.c')
S_src := $(shell find $(board_dir) -name '*.S')
lds := $(board_dir)/kernel.lds

CC_FLAGS += -march=armv6-m
