#include "memory-map.h"
#include "drivers/dbgu.h"
#include "printf.h"


/* this function prints ../fluff/banner.txt */
void print_banner() {
    multiprint('M', 29);
    dbgu_put_byte('W');
    dbgu_put_byte('X');
    dbgu_put_byte('O');
    dbgu_put_byte('d');
    multiprint('o', 3);
    dbgu_put_byte('d');
    dbgu_put_byte('O');
    dbgu_put_byte('X');
    dbgu_put_byte('W');
    multiprint('M', 29);
    dbgu_put_byte('\n');
    multiprint('M', 27);
    dbgu_put_byte('N');
    dbgu_put_byte('O');
    dbgu_put_byte('o');
    dbgu_put_byte(';');
    dbgu_put_byte('\'');
    multiprint(' ', 5);
    dbgu_put_byte('\'');
    dbgu_put_byte(';');
    dbgu_put_byte('l');
    dbgu_put_byte('O');
    dbgu_put_byte('N');
    multiprint('M', 27);
    dbgu_put_byte('\n');
    multiprint('M', 26);
    dbgu_put_byte('K');
    dbgu_put_byte('c');
    multiprint(' ', 13);
    dbgu_put_byte('c');
    dbgu_put_byte('K');
    multiprint('M', 26);
    dbgu_put_byte('\n');
    multiprint('M', 19);
    multiprint('W', 2);
    multiprint('M', 4);
    dbgu_put_byte('K');
    dbgu_put_byte(':');
    multiprint(' ', 15);
    dbgu_put_byte(':');
    dbgu_put_byte('K');
    multiprint('M', 4);
    multiprint('W', 2);
    multiprint('M', 19);
    dbgu_put_byte('\n');
    multiprint('M', 15);
    dbgu_put_byte('W');
    dbgu_put_byte('K');
    dbgu_put_byte('d');
    dbgu_put_byte('c');
    multiprint(':', 2);
    dbgu_put_byte('l');
    dbgu_put_byte('x');
    dbgu_put_byte('X');
    dbgu_put_byte('M');
    dbgu_put_byte('O');
    dbgu_put_byte('\'');
    multiprint(' ', 15);
    dbgu_put_byte('\'');
    dbgu_put_byte('O');
    dbgu_put_byte('M');
    dbgu_put_byte('X');
    dbgu_put_byte('x');
    dbgu_put_byte('l');
    multiprint(':', 2);
    dbgu_put_byte('c');
    dbgu_put_byte('d');
    dbgu_put_byte('K');
    dbgu_put_byte('W');
    multiprint('M', 15);
    dbgu_put_byte('\n');
    multiprint('M', 15);
    dbgu_put_byte('O');
    dbgu_put_byte(',');
    dbgu_put_byte(' ');
    dbgu_put_byte(',');
    multiprint('l', 2);
    dbgu_put_byte('\'');
    dbgu_put_byte(' ');
    dbgu_put_byte('c');
    dbgu_put_byte('X');
    dbgu_put_byte('0');
    dbgu_put_byte(',');
    multiprint(' ', 15);
    dbgu_put_byte(',');
    dbgu_put_byte('0');
    dbgu_put_byte('X');
    dbgu_put_byte('l');
    dbgu_put_byte(' ');
    dbgu_put_byte('\'');
    multiprint('l', 2);
    dbgu_put_byte(',');
    dbgu_put_byte(' ');
    dbgu_put_byte(',');
    dbgu_put_byte('O');
    multiprint('M', 15);
    dbgu_put_byte('\n');
    multiprint('M', 15);
    dbgu_put_byte('K');
    dbgu_put_byte('d');
    dbgu_put_byte('k');
    dbgu_put_byte('X');
    dbgu_put_byte('W');
    dbgu_put_byte('N');
    dbgu_put_byte('o');
    dbgu_put_byte(' ');
    dbgu_put_byte(',');
    dbgu_put_byte('O');
    dbgu_put_byte('N');
    dbgu_put_byte('o');
    multiprint(' ', 15);
    dbgu_put_byte('o');
    dbgu_put_byte('N');
    dbgu_put_byte('O');
    dbgu_put_byte(',');
    dbgu_put_byte(' ');
    dbgu_put_byte('o');
    dbgu_put_byte('N');
    dbgu_put_byte('W');
    dbgu_put_byte('X');
    dbgu_put_byte('k');
    dbgu_put_byte('d');
    dbgu_put_byte('K');
    multiprint('M', 15);
    dbgu_put_byte('\n');
    multiprint('M', 20);
    dbgu_put_byte('X');
    dbgu_put_byte('c');
    dbgu_put_byte(' ');
    dbgu_put_byte(';');
    dbgu_put_byte('K');
    dbgu_put_byte('M');
    dbgu_put_byte('X');
    dbgu_put_byte('c');
    multiprint(' ', 13);
    dbgu_put_byte('l');
    dbgu_put_byte('X');
    dbgu_put_byte('M');
    dbgu_put_byte('K');
    dbgu_put_byte(';');
    dbgu_put_byte(' ');
    dbgu_put_byte('c');
    dbgu_put_byte('X');
    multiprint('M', 20);
    dbgu_put_byte('\n');
    multiprint('M', 11);
    dbgu_put_byte('X');
    dbgu_put_byte('0');
    multiprint('k', 2);
    dbgu_put_byte('O');
    dbgu_put_byte('K');
    dbgu_put_byte('W');
    dbgu_put_byte('M');
    dbgu_put_byte('N');
    dbgu_put_byte('d');
    multiprint(' ', 2);
    dbgu_put_byte('x');
    dbgu_put_byte('W');
    multiprint('M', 2);
    dbgu_put_byte('X');
    dbgu_put_byte('l');
    multiprint(' ', 11);
    dbgu_put_byte('l');
    dbgu_put_byte('X');
    multiprint('M', 2);
    dbgu_put_byte('W');
    dbgu_put_byte('x');
    multiprint(' ', 2);
    dbgu_put_byte('d');
    dbgu_put_byte('N');
    dbgu_put_byte('M');
    dbgu_put_byte('W');
    dbgu_put_byte('K');
    dbgu_put_byte('O');
    multiprint('k', 2);
    dbgu_put_byte('0');
    dbgu_put_byte('N');
    multiprint('M', 11);
    dbgu_put_byte('\n');
    multiprint('M', 9);
    dbgu_put_byte('X');
    dbgu_put_byte('o');
    dbgu_put_byte(',');
    multiprint(' ', 4);
    dbgu_put_byte('\'');
    dbgu_put_byte('l');
    dbgu_put_byte('K');
    dbgu_put_byte('k');
    dbgu_put_byte('\'');
    dbgu_put_byte(' ');
    dbgu_put_byte('c');
    dbgu_put_byte('X');
    multiprint('M', 3);
    dbgu_put_byte('W');
    dbgu_put_byte('x');
    multiprint(' ', 11);
    dbgu_put_byte('x');
    multiprint('M', 4);
    dbgu_put_byte('X');
    dbgu_put_byte('c');
    dbgu_put_byte(' ');
    dbgu_put_byte('\'');
    dbgu_put_byte('k');
    dbgu_put_byte('K');
    dbgu_put_byte('l');
    dbgu_put_byte('\'');
    multiprint(' ', 4);
    dbgu_put_byte(',');
    dbgu_put_byte('d');
    dbgu_put_byte('X');
    multiprint('M', 9);
    dbgu_put_byte('\n');
    multiprint('M', 8);
    dbgu_put_byte('N');
    dbgu_put_byte('l');
    dbgu_put_byte(' ');
    dbgu_put_byte(':');
    dbgu_put_byte('k');
    dbgu_put_byte('0');
    dbgu_put_byte('k');
    dbgu_put_byte('c');
    multiprint(' ', 2);
    multiprint(',', 2);
    multiprint(' ', 2);
    dbgu_put_byte('d');
    dbgu_put_byte('W');
    multiprint('M', 3);
    dbgu_put_byte('W');
    dbgu_put_byte('k');
    dbgu_put_byte('\'');
    multiprint(' ', 9);
    dbgu_put_byte('\'');
    dbgu_put_byte('k');
    multiprint('M', 4);
    dbgu_put_byte('W');
    dbgu_put_byte('d');
    multiprint(' ', 2);
    multiprint(',', 2);
    multiprint(' ', 2);
    dbgu_put_byte('c');
    dbgu_put_byte('O');
    dbgu_put_byte('0');
    dbgu_put_byte('k');
    dbgu_put_byte(':');
    dbgu_put_byte(' ');
    dbgu_put_byte('l');
    dbgu_put_byte('N');
    multiprint('M', 8);
    dbgu_put_byte('\n');
    multiprint('M', 8);
    dbgu_put_byte('X');
    dbgu_put_byte(':');
    dbgu_put_byte(' ');
    dbgu_put_byte('c');
    dbgu_put_byte('0');
    dbgu_put_byte('W');
    dbgu_put_byte('M');
    dbgu_put_byte('N');
    dbgu_put_byte('o');
    multiprint(' ', 5);
    dbgu_put_byte('x');
    dbgu_put_byte('W');
    multiprint('M', 3);
    dbgu_put_byte('W');
    dbgu_put_byte('O');
    dbgu_put_byte(';');
    multiprint(' ', 9);
    dbgu_put_byte(';');
    dbgu_put_byte('O');
    dbgu_put_byte('W');
    multiprint('M', 4);
    dbgu_put_byte('x');
    multiprint(' ', 5);
    dbgu_put_byte('o');
    dbgu_put_byte('N');
    dbgu_put_byte('M');
    dbgu_put_byte('W');
    dbgu_put_byte('0');
    dbgu_put_byte('c');
    dbgu_put_byte(' ');
    dbgu_put_byte(':');
    dbgu_put_byte('X');
    multiprint('M', 8);
    dbgu_put_byte('\n');
    multiprint('M', 8);
    dbgu_put_byte('W');
    dbgu_put_byte('O');
    dbgu_put_byte(':');
    dbgu_put_byte('\'');
    dbgu_put_byte(',');
    dbgu_put_byte('O');
    multiprint('M', 2);
    dbgu_put_byte('O');
    dbgu_put_byte(',');
    multiprint(' ', 4);
    dbgu_put_byte(';');
    dbgu_put_byte('x');
    dbgu_put_byte('0');
    dbgu_put_byte('O');
    dbgu_put_byte('x');
    dbgu_put_byte('c');
    dbgu_put_byte('\'');
    multiprint(' ', 11);
    dbgu_put_byte('\'');
    dbgu_put_byte('c');
    dbgu_put_byte('x');
    multiprint('O', 2);
    dbgu_put_byte('x');
    dbgu_put_byte(';');
    multiprint(' ', 4);
    dbgu_put_byte(',');
    dbgu_put_byte('O');
    multiprint('M', 2);
    dbgu_put_byte('O');
    dbgu_put_byte(',');
    dbgu_put_byte('\'');
    dbgu_put_byte('c');
    dbgu_put_byte('O');
    dbgu_put_byte('W');
    multiprint('M', 8);
    dbgu_put_byte('\n');
    multiprint('M', 10);
    dbgu_put_byte('W');
    dbgu_put_byte('K');
    dbgu_put_byte('0');
    dbgu_put_byte('X');
    multiprint('M', 2);
    dbgu_put_byte('K');
    dbgu_put_byte(';');
    multiprint(' ', 33);
    dbgu_put_byte(';');
    dbgu_put_byte('K');
    multiprint('M', 2);
    dbgu_put_byte('X');
    dbgu_put_byte('0');
    dbgu_put_byte('K');
    dbgu_put_byte('W');
    multiprint('M', 10);
    dbgu_put_byte('\n');
    multiprint('M', 16);
    dbgu_put_byte('W');
    dbgu_put_byte('x');
    dbgu_put_byte('\'');
    multiprint(' ', 31);
    dbgu_put_byte('\'');
    dbgu_put_byte('x');
    dbgu_put_byte('W');
    multiprint('M', 16);
    dbgu_put_byte('\n');
    multiprint('M', 12);
    dbgu_put_byte('N');
    dbgu_put_byte('O');
    dbgu_put_byte('d');
    multiprint('o', 3);
    dbgu_put_byte(';');
    multiprint(' ', 14);
    dbgu_put_byte('c');
    dbgu_put_byte('d');
    dbgu_put_byte('c');
    multiprint(' ', 14);
    dbgu_put_byte(';');
    multiprint('o', 3);
    dbgu_put_byte('d');
    dbgu_put_byte('O');
    dbgu_put_byte('N');
    multiprint('M', 12);
    dbgu_put_byte('\n');
    multiprint('M', 10);
    dbgu_put_byte('W');
    dbgu_put_byte('0');
    dbgu_put_byte(':');
    multiprint(' ', 13);
    dbgu_put_byte(';');
    dbgu_put_byte(',');
    multiprint(' ', 4);
    dbgu_put_byte('c');
    dbgu_put_byte('X');
    dbgu_put_byte('M');
    dbgu_put_byte('X');
    dbgu_put_byte('c');
    multiprint(' ', 4);
    dbgu_put_byte(',');
    dbgu_put_byte(';');
    multiprint(' ', 13);
    dbgu_put_byte(':');
    dbgu_put_byte('0');
    dbgu_put_byte('W');
    multiprint('M', 10);
    dbgu_put_byte('\n');
    multiprint('M', 10);
    dbgu_put_byte('K');
    dbgu_put_byte(';');
    dbgu_put_byte(' ');
    dbgu_put_byte(',');
    dbgu_put_byte('d');
    dbgu_put_byte('O');
    dbgu_put_byte('0');
    dbgu_put_byte('O');
    dbgu_put_byte('k');
    dbgu_put_byte('x');
    dbgu_put_byte('o');
    multiprint('l', 3);
    multiprint('d', 2);
    dbgu_put_byte('c');
    multiprint(' ', 3);
    dbgu_put_byte(',');
    dbgu_put_byte('d');
    dbgu_put_byte('X');
    multiprint('M', 3);
    dbgu_put_byte('X');
    dbgu_put_byte('d');
    dbgu_put_byte(',');
    multiprint(' ', 3);
    dbgu_put_byte('c');
    multiprint('d', 2);
    multiprint('l', 3);
    dbgu_put_byte('o');
    dbgu_put_byte('x');
    dbgu_put_byte('k');
    dbgu_put_byte('O');
    dbgu_put_byte('0');
    dbgu_put_byte('O');
    dbgu_put_byte('d');
    dbgu_put_byte(',');
    dbgu_put_byte(' ');
    dbgu_put_byte(';');
    dbgu_put_byte('K');
    multiprint('M', 10);
    dbgu_put_byte('\n');
    multiprint('M', 10);
    dbgu_put_byte('O');
    dbgu_put_byte('\'');
    dbgu_put_byte(' ');
    dbgu_put_byte('l');
    dbgu_put_byte('N');
    dbgu_put_byte('M');
    dbgu_put_byte('W');
    dbgu_put_byte('0');
    multiprint('d', 2);
    dbgu_put_byte('K');
    multiprint('M', 2);
    dbgu_put_byte('X');
    dbgu_put_byte('d');
    dbgu_put_byte('\'');
    multiprint(' ', 2);
    dbgu_put_byte(';');
    dbgu_put_byte('d');
    dbgu_put_byte('X');
    dbgu_put_byte('W');
    multiprint('M', 5);
    dbgu_put_byte('W');
    dbgu_put_byte('K');
    dbgu_put_byte('d');
    dbgu_put_byte(';');
    multiprint(' ', 2);
    dbgu_put_byte('\'');
    dbgu_put_byte('d');
    dbgu_put_byte('X');
    multiprint('M', 2);
    dbgu_put_byte('K');
    dbgu_put_byte('d');
    dbgu_put_byte('o');
    dbgu_put_byte('0');
    dbgu_put_byte('W');
    dbgu_put_byte('M');
    dbgu_put_byte('N');
    dbgu_put_byte('l');
    dbgu_put_byte(' ');
    dbgu_put_byte(',');
    dbgu_put_byte('O');
    multiprint('M', 10);
    dbgu_put_byte('\n');
    multiprint('M', 10);
    dbgu_put_byte('X');
    dbgu_put_byte('l');
    dbgu_put_byte(' ');
    dbgu_put_byte('\'');
    dbgu_put_byte('x');
    dbgu_put_byte('K');
    dbgu_put_byte('d');
    dbgu_put_byte('\'');
    dbgu_put_byte(' ');
    dbgu_put_byte(';');
    dbgu_put_byte('K');
    dbgu_put_byte('W');
    dbgu_put_byte('O');
    dbgu_put_byte(';');
    dbgu_put_byte(' ');
    dbgu_put_byte('\'');
    dbgu_put_byte('c');
    dbgu_put_byte('k');
    dbgu_put_byte('N');
    multiprint('M', 11);
    dbgu_put_byte('N');
    dbgu_put_byte('k');
    dbgu_put_byte('c');
    dbgu_put_byte('\'');
    dbgu_put_byte(' ');
    dbgu_put_byte(';');
    dbgu_put_byte('O');
    dbgu_put_byte('W');
    dbgu_put_byte('K');
    dbgu_put_byte(';');
    dbgu_put_byte(' ');
    dbgu_put_byte('\'');
    dbgu_put_byte('d');
    dbgu_put_byte('K');
    dbgu_put_byte('x');
    dbgu_put_byte('\'');
    dbgu_put_byte(' ');
    dbgu_put_byte('l');
    dbgu_put_byte('N');
    multiprint('M', 10);
    dbgu_put_byte('\n');
    multiprint('M', 11);
    dbgu_put_byte('N');
    dbgu_put_byte('k');
    dbgu_put_byte(':');
    multiprint(',', 2);
    dbgu_put_byte(' ');
    dbgu_put_byte('\'');
    dbgu_put_byte('c');
    dbgu_put_byte('0');
    dbgu_put_byte('M');
    dbgu_put_byte('0');
    dbgu_put_byte(';');
    dbgu_put_byte(' ');
    dbgu_put_byte('c');
    dbgu_put_byte('0');
    dbgu_put_byte('W');
    dbgu_put_byte('M');
    dbgu_put_byte('K');
    multiprint('d', 2);
    dbgu_put_byte('X');
    multiprint('M', 5);
    dbgu_put_byte('X');
    multiprint('d', 2);
    dbgu_put_byte('K');
    dbgu_put_byte('M');
    dbgu_put_byte('W');
    dbgu_put_byte('0');
    dbgu_put_byte('c');
    dbgu_put_byte(' ');
    dbgu_put_byte(';');
    dbgu_put_byte('0');
    dbgu_put_byte('W');
    dbgu_put_byte('0');
    dbgu_put_byte('c');
    dbgu_put_byte('\'');
    dbgu_put_byte(' ');
    multiprint(',', 2);
    dbgu_put_byte(':');
    dbgu_put_byte('k');
    dbgu_put_byte('N');
    multiprint('M', 11);
    dbgu_put_byte('\n');
    multiprint('M', 13);
    dbgu_put_byte('W');
    dbgu_put_byte('K');
    multiprint('O', 2);
    dbgu_put_byte('K');
    dbgu_put_byte('W');
    multiprint('M', 2);
    dbgu_put_byte('k');
    multiprint(' ', 2);
    dbgu_put_byte('k');
    multiprint('M', 2);
    dbgu_put_byte('X');
    dbgu_put_byte('l');
    multiprint(' ', 2);
    dbgu_put_byte('k');
    multiprint('M', 5);
    dbgu_put_byte('k');
    multiprint(' ', 2);
    dbgu_put_byte('l');
    dbgu_put_byte('N');
    dbgu_put_byte('M');
    dbgu_put_byte('W');
    dbgu_put_byte('k');
    dbgu_put_byte('\'');
    dbgu_put_byte(' ');
    dbgu_put_byte('k');
    multiprint('M', 2);
    dbgu_put_byte('W');
    dbgu_put_byte('K');
    dbgu_put_byte('O');
    dbgu_put_byte('0');
    dbgu_put_byte('K');
    dbgu_put_byte('W');
    multiprint('M', 13);
    dbgu_put_byte('\n');
    multiprint('M', 21);
    dbgu_put_byte('X');
    dbgu_put_byte('c');
    dbgu_put_byte(' ');
    dbgu_put_byte(';');
    dbgu_put_byte('x');
    dbgu_put_byte('0');
    dbgu_put_byte('x');
    dbgu_put_byte(',');
    dbgu_put_byte(' ');
    dbgu_put_byte(':');
    dbgu_put_byte('K');
    multiprint('M', 5);
    dbgu_put_byte('K');
    dbgu_put_byte(':');
    dbgu_put_byte(' ');
    dbgu_put_byte(',');
    dbgu_put_byte('x');
    dbgu_put_byte('0');
    dbgu_put_byte('x');
    dbgu_put_byte(';');
    dbgu_put_byte(' ');
    dbgu_put_byte('c');
    dbgu_put_byte('X');
    multiprint('M', 21);
    dbgu_put_byte('\n');
    multiprint('M', 22);
    dbgu_put_byte('X');
    dbgu_put_byte('x');
    dbgu_put_byte(':');
    multiprint(',', 3);
    dbgu_put_byte(';');
    dbgu_put_byte('l');
    dbgu_put_byte('K');
    dbgu_put_byte('W');
    multiprint('M', 6);
    dbgu_put_byte('K');
    dbgu_put_byte('l');
    dbgu_put_byte(';');
    multiprint(',', 3);
    dbgu_put_byte(':');
    dbgu_put_byte('x');
    dbgu_put_byte('X');
    multiprint('M', 22);
    dbgu_put_byte('\n');
    multiprint('M', 24);
    dbgu_put_byte('W');
    dbgu_put_byte('K');
    multiprint('0', 2);
    dbgu_put_byte('X');
    dbgu_put_byte('W');
    multiprint('M', 9);
    dbgu_put_byte('W');
    dbgu_put_byte('X');
    multiprint('0', 2);
    dbgu_put_byte('K');
    dbgu_put_byte('W');
    multiprint('M', 24);
    dbgu_put_byte('\n');
    multiprint(' ', 29);
    dbgu_put_byte('8');
    multiprint('"', 3);
    multiprint('8', 2);
    dbgu_put_byte(' ');
    dbgu_put_byte('8');
    multiprint('"', 4);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    dbgu_put_byte('\n');
    multiprint('e', 5);
    dbgu_put_byte(' ');
    multiprint('e', 4);
    dbgu_put_byte(' ');
    multiprint('e', 5);
    dbgu_put_byte(' ');
    multiprint('e', 5);
    dbgu_put_byte(' ');
    multiprint('e', 5);
    dbgu_put_byte(' ');
    dbgu_put_byte('8');
    multiprint(' ', 4);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    dbgu_put_byte('8');
    multiprint(' ', 6);
    dbgu_put_byte('\n');
    dbgu_put_byte('8');
    multiprint(' ', 2);
    multiprint('8', 2);
    dbgu_put_byte(' ');
    dbgu_put_byte('8');
    multiprint(' ', 2);
    dbgu_put_byte('8');
    multiprint(' ', 3);
    dbgu_put_byte('8');
    multiprint(' ', 3);
    dbgu_put_byte('8');
    multiprint(' ', 2);
    multiprint('8', 2);
    dbgu_put_byte(' ');
    dbgu_put_byte('8');
    multiprint(' ', 3);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    dbgu_put_byte('8');
    multiprint(' ', 4);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    dbgu_put_byte('8');
    multiprint('e', 5);
    dbgu_put_byte(' ');
    dbgu_put_byte('\n');
    dbgu_put_byte('8');
    multiprint(' ', 3);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    dbgu_put_byte('8');
    dbgu_put_byte('e');
    multiprint(' ', 5);
    dbgu_put_byte('8');
    dbgu_put_byte('e');
    multiprint(' ', 2);
    dbgu_put_byte('8');
    multiprint(' ', 3);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    dbgu_put_byte('8');
    multiprint('e', 3);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    dbgu_put_byte('8');
    multiprint(' ', 4);
    dbgu_put_byte('8');
    multiprint(' ', 5);
    multiprint('8', 2);
    dbgu_put_byte(' ');
    dbgu_put_byte('\n');
    dbgu_put_byte('8');
    multiprint(' ', 3);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    multiprint('8', 2);
    multiprint(' ', 5);
    multiprint('8', 2);
    multiprint(' ', 2);
    dbgu_put_byte('8');
    multiprint(' ', 3);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    multiprint('8', 2);
    multiprint(' ', 4);
    dbgu_put_byte('8');
    multiprint(' ', 4);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    dbgu_put_byte('e');
    multiprint(' ', 3);
    multiprint('8', 2);
    dbgu_put_byte(' ');
    dbgu_put_byte('\n');
    dbgu_put_byte('8');
    multiprint('e', 3);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    multiprint('8', 2);
    dbgu_put_byte('e');
    dbgu_put_byte('8');
    multiprint(' ', 3);
    multiprint('8', 2);
    multiprint(' ', 2);
    dbgu_put_byte('8');
    multiprint('e', 3);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    multiprint('8', 2);
    multiprint(' ', 4);
    dbgu_put_byte('8');
    multiprint('e', 4);
    dbgu_put_byte('8');
    dbgu_put_byte(' ');
    dbgu_put_byte('8');
    multiprint('e', 3);
    multiprint('8', 2);
    dbgu_put_byte(' ');
    dbgu_put_byte('\n');
    multiprint(' ', 38);
    dbgu_put_byte('(');
    dbgu_put_byte('c');
    dbgu_put_byte(')');
    dbgu_put_byte(' ');
    dbgu_put_byte('P');
    dbgu_put_byte('a');
    dbgu_put_byte('u');
    dbgu_put_byte('l');
    dbgu_put_byte(' ');
    dbgu_put_byte('W');
    dbgu_put_byte('e');
    dbgu_put_byte('i');
    multiprint('s', 2);
    dbgu_put_byte(' ');
    dbgu_put_byte('&');
    dbgu_put_byte(' ');
    dbgu_put_byte('F');
    dbgu_put_byte('a');
    dbgu_put_byte('b');
    dbgu_put_byte('i');
    dbgu_put_byte('a');
    dbgu_put_byte('n');
    dbgu_put_byte(' ');
    dbgu_put_byte('J');
    dbgu_put_byte('e');
    dbgu_put_byte('z');
    dbgu_put_byte('u');
    dbgu_put_byte('i');
    dbgu_put_byte('t');
    dbgu_put_byte('a');
    dbgu_put_byte('\n');
    multiprint('*', 69);
    dbgu_put_byte('\n');
}
